modLoader="javafml"
loaderVersion="[41,)"
license="LGPL v2.1"
issueTrackerURL="https://github.com/EnderTurret/ItemSubs/issues"

[[mods]]
    modId="itemsubs"
    displayName="Item Subs"
    description='''
    Adds subaquatic item transport in the form of item submarines!
    '''
    version="${file.jarVersion}"
    authors="EnderTurret, Dustskys"
    displayURL="https://github.com/EnderTurret/ItemSubs"

[[dependencies.itemsubs]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.94,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.itemsubs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.19.1)"
    ordering="NONE"
    side="BOTH"