modLoader="javafml"
loaderVersion="[40,)"
license="LGPL v2.1"
issueTrackerURL="https://github.com/EnderTurret/ItemSubs/issues"

[[mods]]
    modId="itemsubs"
    displayName="Item Subs"
    description='''
    Adds subaquatic item transport in the form of item submarines!
    '''
    version="${file.jarVersion}"
    authors="EnderTurret, Dustskys"
    displayURL="https://github.com/EnderTurret/ItemSubs"
    logoFile="icon.png"

[[dependencies.itemsubs]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.itemsubs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"