modLoader="javafml"
loaderVersion="[41,)"
license="LGPL v2.1"
[[mods]]
    modId="itemsubs"
    displayName="Item Subs"
    description='''
    Subaquatic item transport.
    '''
    version="${file.jarVersion}"
    authors="EnderTurret"

[[dependencies.itemsubs]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.94,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.itemsubs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.19.1)"
    ordering="NONE"
    side="BOTH"